filter:
    paths: ["src/"]
checks:
    php: true
build:
    dependencies:
        before:
            - "composer require squizlabs/php_codesniffer ^3.2"
    nodes:
        php70:
            environment:
                php:
                    version: "7.0"

        php71:
            environment:
                php:
                    version: "7.1"
        php72:
            environment:
                php:
                    version: "7.2"
    tests:
        before:
            - "vendor/bin/phpcs"
