filter:
    paths: ["src/"]
checks:
    php: true
build:
    nodes:
        php71:
            environment:
                php:
                    version: "7.1"
        php72:
            environment:
                php:
                    version: "7.2"
        analysis:
            dependencies:
                after:
                    - composer require squizlabs/php_codesniffer ^3.2
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage-clover'
                        coverage:
                            file: 'coverage-clover'
                            format: 'clover'
